# Generated by Django 5.2.17 on 2026-10-02 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_daily_entry_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdateState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('check_error', models.CharField(blank=True, max_length=300)),
                ('latest_sha', models.CharField(blank=True, max_length=40)),
                ('latest_committed_at', models.DateTimeField(blank=True, null=True)),
                ('latest_message', models.CharField(blank=True, max_length=300)),
                ('commits_behind', models.PositiveIntegerField(default=0)),
                ('commit_log', models.JSONField(blank=True, default=list)),
                ('image_available', models.BooleanField(default=False)),
                ('dismissed_sha', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'system update state',
            },
        ),
        migrations.CreateModel(
            name='SystemUpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('from_sha', models.CharField(blank=True, max_length=40)),
                ('to_sha', models.CharField(max_length=40)),
                ('to_tag', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('step', models.CharField(blank=True, max_length=40)),
                ('log', models.TextField(blank=True)),
                ('backup_path', models.CharField(blank=True, max_length=300)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
